spring:
  application:
    name: acs-live-stream-overlay-app

  datasource:
    name: live-stream-overlay-datasource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username:
    password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
